### ISSUE TITLE
Meeting Notes 2016-09-12

### ISSUE THREAD

**Issue by martindholmes** [TheCanadianConfederationDebates/TCCD#17] opened 2016-09-12 18:32 UTC
Present: DH, MH, GL

Two collections which are actually complete can serve as the basis for developing the XHTML-to-TEI conversion:
- BC House of Commons debates are done.
- PEI House of Commons are done (very short).

IV/Erasmus is also done, but being a prose publication is atypical, so we should leave it for now.

There are some inconsistencies in the repo which need to be addressed:
- NB redone needs to replace NB.
- PEI2 should replace PEI.
- Alb_Sask Federal is problematic, with duplication and possibly some missing data.

Since DH best knows what needs to be done there, he will address those issues. Meanwhile, GL will undertake a survey of all the data, listing out what we have, and what phase each set has reached.

For Alb_Sask Provincial, there are Google OCR docs here:
   https://drive.google.com/drive/folders/0B0nS88Hu10fddnpQV3dCMDVkSGc
   These need to be imported, and then specially transformed to match our standard. MH will do this.

Ditto for the Newfoundlander:
   https://drive.google.com/drive/folders/0B0nS88Hu10fdM0syRmtMU0NFVEE

Postcode database: we will have a single point on the db for each postal code, and also a point on the map for each representative. DH will add that db to the repo. Meanwhile, each entry in the personography spreadsheet (representing an individual in a specific seat during a particular debate) will have a single GIS point for the centre of their riding, so that any speech in any debate can be linked through its representative to its "location". DH will use the Vertexer to add GIS points.

Each debate needs to have a legislature and a date range to distinguish it. We need to add this metadata to the corrected OCR, or perhaps to the generated TEI after it's been generated. GL and MH will decide on how best to approach this.

**Comment by DanielHeidt** [comment] 2016-09-12 19:00
I have uploaded 2 GPS / postalcode datasets. The first is from 2015, and simply contains the postal code, lat, long, and city. The second is from https://geocoder.ca/?freedata=1 and the description appears to be similar, but the files are very different. Perhaps they are better, but need to be plugged into the geocoder API? I think the readme file is here: https://geocoder.ca/?services=1.

**Comment by martindholmes** [comment] 2016-09-12 23:44
Where did you put them? I can't see them in the repo.

**Comment by DanielHeidt** [comment] 2016-09-13 16:58
They are in code/postalcodes/

**Comment by martindholmes** [comment] 2016-09-13 18:28
Hi Dan,

They don't seem to be there there:

<https://github.com/TheCanadianConfederationDebates/TCCD/tree/master/code>

Perhaps you committed them locally and didn't push, or put them in a 
different branch?

Incidentally, there are a lot of branches you've created, two of which 
are still unmerged. I'm not sure that it's necessary to create branches 
like this, especially when you're just adding new data. Can you look at 
your unmerged branches and either merge them if you think they should be 
merged, or delete them if they're obsolete?

<https://github.com/TheCanadianConfederationDebates/TCCD/branches/all>

Cheers,
Martin

**Comment by DanielHeidt** [comment] 2016-09-13 18:52
Hi Martin,

Good catch on the branches. Not sure what happened here. I’ve merged / deleted all but one - which - it turns out - resolves the Alb-Sask missing files. Since I uploaded new files, there is now a conflict, and we’ll need to resolve this at the command line. I know what each of the copies hold, but I think it would be best if you do this during our next meeting when I can confirm what’s there and you can execute the right command.

The postal code files weren’t uploading because some of them were too large for a free github account. I have uploaded one of them to the repo, and the other can be downloaded at https://www.dropbox.com/sh/t7e1hdjxzr3fkaz/AACaVEdL_Xiewk6_B78_R7Qga?dl=0.

Sorry about the confusion!


Dan

**Comment by martindholmes** [comment] 2016-09-13 19:17
HI Dan,

Does the master branch now contain what it should for Alb_Sask? If so, 
you can just delete the unwanted branch.

Cheers,
Martin

**Comment by DanielHeidt** [comment] 2016-09-13 19:19
Hi Martin,

The master branch lacks the hocr_edited directory (which I think I can reproduce another way, but I’d like the opportunity to check against the conflicted version on the repo).

Dan

**Closed** 2017-11-21 18:10 UTC
Labels: Meeting Notes
